### ISSUE TITLE
Without NX_WORKSPACE_ROOT_PATH I got an error about missing nx.json file.

### ISSUE THREAD

**Issue by tamascsaba** [e-square-io/nx-github-actions#56]
Our `nx.json` is under a subfolder in the repository. I tired to use `workingDirectory `, but is is not working. The only solution is setting up `NX_WORKSPACE_ROOT_PATH` environment variable.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/3479963/187927448-89f9c33c-5bff-4083-b18e-55fb85483216.png">

<img width="952" alt="image" src="https://user-images.githubusercontent.com/3479963/187926539-ad1547ca-1a57-450f-8f55-d62bf3acd1ff.png">

**Comment by ronnetzer** [comment]
@tamascsaba Do you also need to set this variable when using `nx-distributed-task` or `workingDirectory` is working as expected over there?
